name: Tests
on:
  push:
    branches: "main"
  pull_request:
    branches: "*"
jobs:
  # Run "pre-commit run --all-files"
  pre-commit:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # ref: https://github.com/pre-commit/action
      - uses: pre-commit/action@v2.0.0
      - name: Help message if pre-commit fail
        if: ${{ failure() }}
        run: |
          echo "You can install pre-commit hooks to automatically run formatting"
          echo "on each commit with:"
          echo "    pre-commit install"
          echo "or you can run by hand on staged files with"
          echo "    pre-commit run"
          echo "or after-the-fact on already committed files with"
          echo "    pre-commit run --all-files"

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "pypy-3.7"]
        exclude:
          - os: "ubuntu-latest"
            python-version: "3.6"
          - os: "windows-latest"
            python-version: "pypy-3.7"
          - os: "macos-latest"
            python-version: "3.8"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Point at Jupyter Server branch with terminals removed.
        run: |
          pip install -U git+https://github.com/Zsailer/jupyter_server.git@jupyter_server_terminals
      - name: Install the Python dependencies
        run: |
          pip install -e ".[test]" codecov
      - name: List installed packages
        run: |
          pip freeze
          pip check
      - name: Run the tests with Coverage
        if: ${{ !startsWith(matrix.python-version, 'pypy') && !startsWith(runner.os, 'Windows') }}
        run: |
          pytest -vv jupyter_server_terminals --cov jupyter_server_terminals --cov-branch --cov-report term-missing:skip-covered
      - name: Run the tests on pypy and Windows
        if: ${{ startsWith(matrix.python-version, 'pypy') || startsWith(runner.os, 'Windows') }}
        run: |
          pytest -vv jupyter_server_terminals
      - name: Coverage
        if: ${{ !startsWith(matrix.python-version, 'pypy') && !startsWith(runner.os, 'Windows') }}
        run: |
          codecov
      - name: Test full install
        if: ${{ !startsWith(matrix.python-version, 'pypy') && !startsWith(runner.os, 'Windows') }}
        run: |
          python -m venv test_install
          ./test_install/bin/python -m pip install -U pip
          ./test_install/bin/python -m pip install ".[test]"
          pushd test_install
          ./bin/pytest --pyargs jupyter_server_terminals
          popd
